### PR TITLE
Lesson 3 auth feature

### PR DESCRIPTION
**Pull request by Kromelky**

### CODE REVIEW

**Comment by Kromelky** [comment]
> Wouldn't it be better to keep http.get() method at both 81 and 110 lines?
Http.NewRequest implemented with client might be a little overkill.

I'm just using it because of adding Auth token directly to request. Didn't find how to add a header with hhtp.get method

**Review by EndofSmallSanctuary — COMMENTED** [review]
After our conversation, http.NewRequest() implementation seems meaningful for me

**Comment by Kromelky** [comment]
> We are dealing with similar request creating structure at both funcs. There is a sense of grouping them up in a single function
Good idia. I'll do it later. You can insert comments directly in code, in "files change" tab. FYI

**Comment by EndofSmallSanctuary** [comment]
> > We are dealing with similar request creating structure at both funcs. There is a sense of grouping them up in a single function
> > Good idia. I'll do it later. You can insert comments directly in code, in "files change" tab. FYI

Okay, it's clear for me now. I will merge this pr, and wait for future changes then

**Review by EndofSmallSanctuary — APPROVED** [review]

**Pull request merged**
